# keep version only for graphviz
version: '3.8'
name: otel-lgtm-dotnet
services:
  sol-gateway:
    build:
      context: ../..
      dockerfile: demo/Dockerfile.vector
    command: ["--config", "/etc/sol/sol-gateway.yaml"]
    volumes:
      - ./sol/sol-gateway.yaml:/etc/sol/sol-gateway.yaml:ro
    networks:
      - bridge
    depends_on:
      - loki
      - mimir
      - sol-loadbalancer
  sol-loadbalancer:
    build:
      context: ../..
      dockerfile: demo/Dockerfile.vector
    command: ["--config", "/etc/sol/sol-loadbalancer.yaml"]
    volumes:
      - ./sol/sol-loadbalancer.yaml:/etc/sol/sol-loadbalancer.yaml/:ro
    networks:
      - bridge
    depends_on:
      - sol-collector
  sol-collector:
    build:
      context: ../..
      dockerfile: demo/Dockerfile.vector
    command: ["--config", "/etc/sol/sol-collector.yaml"]
    volumes:
      - ./sol/sol-collector.yaml:/etc/sol/sol-collector.yaml:ro
    networks:
      - bridge
    depends_on:
      - tempo
      - mimir
    deploy:
      replicas: 2

  curl:
    image: curlimages/curl:8.6.0
    networks:
      - bridge
    entrypoint: sh -c "watch -n 0.1 -d -- /script/curl.sh 2>&1 > /dev/null"
    volumes:
      - ./curl:/script:ro
    depends_on:
      - client
    deploy:
      replicas: 1

  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=persons
      - POSTGRES_PASSWORD=ReallyBadPassword
    networks:
      - bridge
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 5s

  client:
    build: 
      context: ./client
      dockerfile: ../dotnet.Dockerfile
    environment:
      - SERVICE_NAME=client
      # - OTEL_TRACES_SAMPLER=parentbased_traceidratio
      # - OTEL_TRACES_SAMPLER_ARG=0.1 # demo parameter
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=demo,deployment.environment=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://sol-gateway:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_METRIC_EXPORT_INTERVAL=10000
    networks:
      - bridge
    depends_on:
      - service
      - sol-gateway
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M

  service:
    build: 
      context: ./service
      dockerfile: ../dotnet.Dockerfile
    environment:
      - SERVICE_NAME=service
      # - OTEL_TRACES_SAMPLER=parentbased_always_on
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=demo,deployment.environment=dev
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://sol-gateway:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_METRIC_EXPORT_INTERVAL=10000
      - FAILURE_RATIO=0.1 # demo parameter
      - LATENCY_RATIO=1 # demo parameter
      - MIN_LATENCY=0 #ms
      - MAX_LATENCY=100 #ms
    networks:
      - bridge
    depends_on:
      db:
        condition: service_healthy
      sol-gateway:
        condition: service_started

    deploy:
      # https://github.com/dotnet/runtime/issues/68967
      # https://www.meziantou.net/round-robin-dns-support-in-dotnet-httpclient.htm
      # https://learn.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-8.0#configure-grpc-client-side-load-balancing
      replicas: 1
      resources:
        limits:
          memory: 300M

  loki:
    image: grafana/loki@sha256:c59b9e928dffd375920b972e936c81e93bf14114c5229fae56a07cc47b15b475 #main with otlp support https://github.com/grafana/loki/pull/10727
    command: -config.file=/etc/loki/local-config.yaml -validation.reject-old-samples=false -query-scheduler.max-outstanding-requests-per-tenant=2048 -querier.max-outstanding-requests-per-tenant=2048
    volumes:
      - ./loki/:/etc/loki/:ro
    networks:
      - bridge

  mimir:
    image: grafana/mimir:2.11.0
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
    command: --config.file=/etc/mimir.yaml -distributor.otel-metric-suffixes-enabled # otel_metric_suffixes_enabled: https://grafana.com/docs/enterprise-metrics/latest/config/reference/#limits
    networks:
      - bridge

  tempo:
    image: grafana/tempo:2.3.1
    volumes:
      - ./tempo/tempo-local.yaml:/etc/tempo.yaml:ro
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - bridge

  grafana:
    image: grafana/grafana-oss:10.3.3
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    networks:
      - bridge
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
    depends_on:
      - mimir
      - loki
      - tempo

networks:
  bridge: