[package]
name = "sol-opentelemetry-proto"
version = "0.1.0"
authors = ["Vector Contributors <vector@datadoghq.com>"]
edition = "2024"
publish = false

[build-dependencies]
prost-build.workspace = true
tonic-build.workspace = true
glob.workspace = true

[dependencies]
bytes.workspace = true
chrono.workspace = true
hex = { version = "0.4.3", default-features = false, features = ["std"] }
lookup = { package = "sol-lookup", path = "../sol-lookup", default-features = false }
ordered-float.workspace = true
upstream-opentelemetry-proto = { package = "opentelemetry-proto", version = "0.27", default-features = false, features = ["full", "with-serde"] }
prost.workspace = true
tonic.workspace = true
vrl.workspace = true
sol-core = { path = "../sol-core", default-features = false }

[dev-dependencies]
sol-buffers = { path = "../sol-buffers", default-features = false }
