#!/bin/sh
set -e

# Add Sol to adm group to read /var/logs
usermod --append --groups adm sol || true

if getent group 'systemd-journal'
then
  # Add Sol to systemd-journal to read journald logs
  usermod --append --groups systemd-journal sol || true
  systemctl daemon-reload || true
fi

if getent group 'systemd-journal-remote'
then
  # Add Sol to systemd-journal-remote to read remote journald logs
  usermod --append --groups systemd-journal-remote sol || true
  systemctl daemon-reload || true
fi

#DEBHELPER#
