#!/bin/sh
set -e

# Add sol:sol user & group
id --user sol >/dev/null 2>&1 || \
  useradd --system --shell /sbin/nologin --home-dir /var/lib/sol --user-group \
    --comment "Sol observability data router" sol

# Create default Sol data directory
mkdir -p /var/lib/sol

# Make sol:sol the owner of the Sol data directory
chown -R sol:sol /var/lib/sol

#DEBHELPER#
