ARG RUST_VERSION=1.92
ARG DEBIAN_RELEASE=trixie
ARG FEATURES=api,sources-opentelemetry,sources-internal_metrics,sinks-console,sinks-opentelemetry,transforms-remap,transforms-tail_sampling,transforms-span_metrics

FROM docker.io/rust:${RUST_VERSION}-${DEBIAN_RELEASE} AS builder
RUN apt-get update && apt-get -y --no-install-recommends install \
    build-essential git clang cmake libclang-dev \
    libsasl2-dev libssl-dev libxxhash-dev zlib1g-dev zlib1g

WORKDIR /vector

COPY . .
ARG FEATURES
RUN scripts/environment/install-protoc.sh
RUN --mount=type=cache,target=/vector/target \
    --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    cargo build --release --bin sol \
    --no-default-features --features $FEATURES && \
    cp target/release/sol .

FROM docker.io/debian:${DEBIAN_RELEASE}-slim
RUN apt-get update && apt-get -y --no-install-recommends install zlib1g ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /vector/vector /usr/bin/sol
RUN mkdir -p /var/lib/sol

RUN ["vector", "--version"]

ENTRYPOINT ["/usr/bin/sol"]
