name: Identify Changes

on:
  workflow_call:
    outputs:
      source:
        value: ${{ jobs.detect.outputs.source }}
      dependencies:
        value: ${{ jobs.detect.outputs.dependencies }}
      proto:
        value: ${{ jobs.detect.outputs.proto }}

jobs:
  detect:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      source: ${{ steps.filter.outputs.source }}
      dependencies: ${{ steps.filter.outputs.dependencies }}
      proto: ${{ steps.filter.outputs.proto }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            source:
              - ".cargo/**"
              - "lib/**"
              - "proto/**"
              - "scripts/**"
              - "src/**"
              - "tests/**"
              - "build.rs"
              - "Cargo.lock"
              - "Cargo.toml"
              - "Makefile"
              - "rust-toolchain.toml"
              - "vdev/**"
            dependencies:
              - "Cargo.toml"
              - "Cargo.lock"
              - "rust-toolchain.toml"
              - "deny.toml"
            proto:
              - "proto/**"
              - "lib/opentelemetry-proto/src/proto/**"
              - "lib/otel-proto-types/src/proto/**"
              - "buf.yaml"
